import "./globals.css";
//components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import GradientBlob from "@/components/GradientBlob";
import CursorGlow from "@/components/CursorGlow";
import ScrollProgress from "@/components/ScrollProgress";
import BackToTop from "@/components/BackToTop";
import DepthField from "@/components/DepthField";

export const metadata = {
  title: "Huzaifa_Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <GradientBlob />
      <DepthField />
      <CursorGlow />
      <div className="site-shell">
        <ScrollProgress />
        <Header />
        <StairTransition/>
        <PageTransition>
        {children}
        </PageTransition>
        <BackToTop />
      </div>
      </body>
    </html>
  );
}
