import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
//components
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import GradientBlob from "@/components/GradientBlob";
import CursorGlow from "@/components/CursorGlow";
import ScrollProgress from "@/components/ScrollProgress";
import BackToTop from "@/components/BackToTop";

const jetbrainsMono = JetBrains_Mono({ 
  subsets: ["latin"],
  weight: ["100","200","300","400","500","600","700","800"],
  variable: '--font-jetbrainsMono',
 });

export const metadata = {
  title: "Huzaifa_Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono.variable}>
      <GradientBlob />
      <CursorGlow />
      <ScrollProgress />
      <Header />
      <StairTransition/>
      <PageTransition>
      {children}
      </PageTransition>
      <BackToTop />
      </body>
    </html>
  );
}
